### ISSUE TITLE
Is it possible not to depend on `py-jsonschema`?

### ISSUE THREAD

**Issue by barracuda156** [Mbed-TLS/mbedtls#8756] opened 2024-01-26 20:20 UTC
### Suggested enhancement

It is desirable to drop dependency on `py-jsonschema`, since due to an unfortunate choice of its upstream it now depends on Rust.

### Justification

Mbed TLS needs this because Rust is a hardly justifiable, huge, broken on some platforms dependency, somewhat questionable security-wise.
(Sure enough, right now it is possible just to refrain from updating `py-jsonschema`, staying with pure-Python version, but that is not a viable solution in the long run, I guess.)

**Comment by gilles-peskine-arm** [comment] 2024-01-28 20:08
Yes, [we want to make it optional](https://github.com/Mbed-TLS/mbedtls/issues/6596).

Note that the problem is not really recent versions of Jsonschema, it's when an upgrade happened recently and pip doesn't find a prebuilt binary (of whatever dependency-of-a-dependency is the problem). This has happened a couple of times already and the problem goes away (at least for platforms that aren't too exotic) once enough binaries are available in the pip ecosystem.

**Comment by barracuda156** [comment] 2024-01-28 21:23
@gilles-peskine-arm Thank you for responding. Having it optional will be great, and gonna solve this issue.

Pre-built binaries aren’t really a solution in a number of cases, both technically (anything aside of a few mainstream platforms won’t have any) and as a matter of principle (I guess most of us will want to be able to build from source even if that is not done every time).

**Comment by paul-elliott-arm** [comment] 2024-01-29 14:58
Closing this as a duplicate of #6596

**Closed by paul-elliott-arm** 2024-01-29 14:58 UTC
