### ISSUE TITLE
BUG: variable 't' set but not used in bignum.c file

### ISSUE THREAD

**Issue by moh3nhadavi** [Mbed-TLS/mbedtls#7508] opened 2023-04-27 11:07 UTC
### Bug Report
I was trying to build [MicroPython](https://github.com/micropython/micropython) for the [unix port](https://github.com/micropython/micropython/tree/master/ports/unix), I faced this error:

```
mbedtls/library/bignum.c:1496:29: error: variable 't' set but not used [-Werror,-Wunused-but-set-variable]
    mbedtls_mpi_uint c = 0, t = 0;
```  

### My Solution

I checked the file `bignum.c` and `mpi_mul_hlp` function. In this function, t is defined and in line 1547, it is `t++;`. By deleting t from this function my problem got solved. 

### System information

Operating system and version: MacOS
Compiler: Clang

**Comment by gilles-peskine-arm** [comment] 2023-04-27 11:47
The underlying issue is that this function has assembly optimizations on some platform, and some platforms need `t` but others (and the pure C fallback) don't use `t`.

What version of Mbed TLS are you using? I think we've seen this issue before, but I thought we'd fixed it. In any case the code in `development` no longer uses that extra variable.

**Comment by moh3nhadavi** [comment] 2023-04-27 12:08
I checked MicroPython, It cloned [this commit](https://github.com/Mbed-TLS/mbedtls/commit/1bc2c9cb8b8fe4659bd94b8ebba5a4c02029b7fa) which is from two years ago. 

It is good to hear that you fixed it.

**Comment by gilles-peskine-arm** [comment] 2023-04-27 12:12
Actually this bug report is a duplicate of https://github.com/Mbed-TLS/mbedtls/issues/7166 which has been fixed in all supported versions of Mbed TLS.

Micropython is using an old commit (1bc2c9cb8b8fe4659bd94b8ebba5a4c02029b7fa) from an old branch of Mbed TLS (mbedtls-2.16) which has not been supported since January 2022. I'm afraid there's nothing we in the Mbed TLS project can do about that.

**Closed by gilles-peskine-arm** 2023-04-27 12:12 UTC
