### ISSUE TITLE
write crt and csr to der APIs uses more than 3K stack

### ISSUE THREAD

**Issue by moshe-shahar** [Mbed-TLS/mbedtls#1613] opened 2018-05-03 09:15 UTC
### Description
- Type: Enhancement
- Priority: Major

mbed TLS build:
Version: 2.8.0 (latest)

---------------------------------------------------------------
## Enhancement

[mbedtls_x509write_crt_der](https://github.com/ARMmbed/mbedtls/blob/005239e3ed5edd6c3c152df73c30c65631b6c299/library/x509write_crt.c#L309) and [mbedtls_x509write_csr_der](https://github.com/ARMmbed/mbedtls/blob/005239e3ed5edd6c3c152df73c30c65631b6c299/library/x509write_csr.c#L139) APIs consume more than 3K stack for local buffers.
That behavior can be a blocker for embedded systems.

**Suggested enhancement**  
Write the DER directly to the user buffer and remove the local buffers _sig_ and _tmp_buf_

**Comment by dbedev** [comment] 2018-06-05 08:57
We also hit the same code when trying to add some extensions. 

Besides pushing the stack usage,  the current 2kb temporary stack variable also limits the maximum size of the asn.1 items to be encoded such as the extensions.

For the time being we have locally worked around it by replacing the hardcoded 2048  with a config define.

Should this not be a bug?

**Comment by tom-cosgrove-arm** [comment] 2023-02-10 15:51
This is as a duplicate of #1859 and #2631, and anyway is fixed by #2632

**Closed by tom-cosgrove-arm** 2023-02-10 15:51 UTC
Labels: enhancement, component-x509
