### ISSUE TITLE
psa_arch_test -> Crypto test 221 failing with mbedtls 3.3.0

### ISSUE THREAD

**Issue by ruchi393** [Mbed-TLS/mbedtls#6959] opened 2023-01-24 06:59 UTC
### Summary
I tried running psa_arch_test with mbedtls 3.3.0. The test 221 fails. Given below is the log.
******************************************

TEST: 221 | DESCRIPTION: Testing crypto key derivation APIs | UT: psa_key_derivation_output_key
[Info] Executing tests from non-secure
[Check 1] Test psa_key_derivation_output_key - Key
[Check 2] Test psa_key_derivation_output_key - Info
[Check 3] Test psa_key_derivation_output_key - Salt
[Check 4] Test psa_key_derivation_output_key - Greater Capacity than available
[Check 5] Test psa_key_derivation_output_key - ECC Public key
[Check 6] Test psa_key_derivation_output_key -  ECC keypair (wrong key length)
        Failed at Checkpoint: 14
        Actual: 0
        Expected: 4294967161

TEST RESULT: FAILED (Error Code=0x1)

******************************************

### System information

Mbed TLS version (number or commit id): 3.3.0
Operating system and version: Baremetal with platform derived from std_c as done in the tests/scripts/psa_compliance_test
Configuration (if not default, please attach `mbedtls_config.h`): NA
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): I have tried with Keil and IAR debugger
Additional environment information: 

### Expected behavior
Test 121 should pass

### Actual behavior
Log below

******************************************

TEST: 221 | DESCRIPTION: Testing crypto key derivation APIs | UT: psa_key_derivation_output_key
[Info] Executing tests from non-secure
[Check 1] Test psa_key_derivation_output_key - Key
[Check 2] Test psa_key_derivation_output_key - Info
[Check 3] Test psa_key_derivation_output_key - Salt
[Check 4] Test psa_key_derivation_output_key - Greater Capacity than available
[Check 5] Test psa_key_derivation_output_key - ECC Public key
[Check 6] Test psa_key_derivation_output_key -  ECC keypair (wrong key length)
        Failed at Checkpoint: 14
        Actual: 0
        Expected: 4294967161

TEST RESULT: FAILED (Error Code=0x1)

******************************************

**Comment by gilles-peskine-arm** [comment] 2023-01-24 10:05
[Also reported against psa-arch-tests](https://github.com/ARM-software/psa-arch-tests/issues/339). I have not investigated on which side the bug is.

**Comment by gilles-peskine-arm** [comment] 2023-01-24 10:07
> Expected: 4294967161

That can't be right: the expected value is `PSA_ERROR_INVALID_ARGUMENT` = -135, not 2^32-135. Hopefully that's just a reporting bug, distinct from the fact that mbedtls returns 0 but psa-arch-tests expect an error.

**Comment by ruchi393** [comment] 2023-01-25 09:03
> > Expected: 4294967161
> 
> That can't be right: the expected value is `PSA_ERROR_INVALID_ARGUMENT` = -135, not 2^32-135. Hopefully that's just a reporting bug, distinct from the fact that mbedtls returns 0 but psa-arch-tests expect an error.

Yes, I think 4294967161 is an aberration. The real issue is that psa-arch-tests expect an error while mbedtls returns 0.

**Comment by paul-elliott-arm** [comment] 2023-01-25 12:57
Reproduced the problem, and I get the correct error report, unlike above.

However, I do not believe this to be a valid negative test, thus not a bug on our side, but on the test side. I have commented on the [linked](https://github.com/ARM-software/psa-arch-tests/issues/339) issue to this effect, and will pursue that there.

Do you have any objection to me closing this issue, as I do not believe this is an MbedTLS bug?

**Comment by ruchi393** [comment] 2023-01-27 06:18
Sure please close this ticket

**Closed** 2023-02-07 11:14 UTC
