### ISSUE TITLE
0x7780 occurs when the MBEDTLS_AES_ALT macro is enabled in TLS1.2 SERVER

### ISSUE THREAD

**Issue by cyyyys** [Mbed-TLS/mbedtls#6590] opened 2022-11-11 08:39 UTC
### Summary
I enabled the MBEDTLS_AES_ALT macro control and implemented the AES hardware algorithm to replace it, but ran the AT SSL create instruction for testing and sent the Encrypted Handshake Message on the client side followed by a Bad record mac on the server side.

ciphersuite: I have tried TLS_RSA_WITH_AES_256_CBC_SHA256，TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 and TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

### System information

Mbed TLS version (number or commit id): 2.25.0

### Expected behavior

ssl is created successfully.

### Actual behavior

return 0x7780, Bad record mac

### Additional information
Some serial port information is displayed:

[16:27:11.771]收←◆[08:27:11.301]MBEDTLS_SSL_CERTIFICATE_VERIFY ret: [0]
[08:27:11.304]ret value in loop: [0]
[08:27:11.307]MBEDTLS_SSL_CLIENT_CHANGE_CIPHER_SPEC ret: [0]
[08:27:11.312]ret value in loop: [0]
[08:27:11.315]^^^^^^ mbedtls_md_hmac_starts ret ^^^^^^ 
[08:27:11.320]^^^^^^ ctx: [514796] ^^^^^^ 
[08:27:11.323]^^^^^^ ctx->md_info: [1083068352] ^^^^^^ 
[08:27:11.329]^^^^^^ ctx->hmac_ctx: [616664] ^^^^^^ 
[08:27:11.334]^^^^^^ SHA-256 ^^^^^^ 
[08:27:11.337]=== mbedtls_md_hmac_starts ret: [0] === 
[08:27:11.342
[16:27:11.814]收←◆]^^^^^^ SHA-256 ^^^^^^ 
[08:27:11.345]=== mbedtls_md_hmac_finish ret: [0] === 
[08:27:11.351]^^^^^^ SHA-256 ^^^^^^ 
[08:27:11.353]^^^^^^ SHA-256 ^^^^^^ 
[08:27:11.356]=== mbedtls_md_hmac_finish ret: [0] === 
[08:27:11.362]^^^^^^ SHA-256 ^^^^^^ 
[08:27:11.364]^^^^^^ SHA-256 ^^^^^^ 
[08:27:11.367]=== mbedtls_md_hmac_finish ret: [0] === 
[08:27:11.373]MBEDTLS_SSL_CLIENT_FINISHED ret: [0]
[08:27:11.378]164641512314562335 
[08:27:11.381]ret value in loop: [0]
[08:27:11.383]=> parse change cipher spec
[16:27:11.867]收←◆----- ssl->in_msgtype: [21] -----
[08:27:11.397]got an alert message, type: [2:20]
[08:27:11.402]is a fatal alert message (msg 20)===>  mbedtls_ssl_handle_message_type: [-30592] <===
[08:27:11.410]***  mbedtls_ssl_read_record: [-30592] ***
[08:27:11.416]66655555666666 
[08:27:11.419]MBEDTLS_SSL_SERVER_CHANGE_CIPHER_SPEC ret: [-30592]
[08:27:11.424]ret value in loop: [-30592]
[08:27:11.427] $$$ ret value: [-30592] $$$
[08:27:11.432]mbedtls_ssl_handshake returned -0x7780
[08:27:11.435]Certificate verified.
[08:27:11.442]Failed to open new connection
[08:27:11.444]ssl Connection failed...
[08:27:11.447]system_config_byte 0

**Comment by wernerlewis** [comment] 2022-11-11 11:15
Thanks for including the serial port information. It appears that the encrypted HMAC being sent during the handshake is invalid, which could be due to an error in your AES_ALT implementation. Have you validated your AES implementation against the default?
If your _ALT implementation is valid, it may also be possible that an AES error is not being caught (see #1092).

**Comment by cyyyys** [comment] 2022-11-12 10:02
@wernerlewis  Thanks for your suggest. I would like to know whether the change of aes algorithm will cause problems with the hmac value, and how does this affect it?

**Comment by cyyyys** [comment] 2022-11-12 10:56
It should be added that no certificate is generated during the network distribution process of the matter, so it is successful. However, the problem occurs after the at creates the certificate public key and private key. There may be a problem with my replacement, but I can't find it at the moment

**Comment by wernerlewis** [comment] 2022-11-14 15:00
The error is being returned after the first encrypted message is sent by the client, at the end of the handshake. If the AES implementation on the client is incorrect, then this message will be invalid when decrypted by the server, and it will respond with bad_record_mac.

**Comment by cyyyys** [comment] 2022-11-15 01:50
> The error is being returned after the first encrypted message is sent by the client, at the end of the handshake. If the AES implementation on the client is incorrect, then this message will be invalid when decrypted by the server, and it will respond with bad_record_mac.

**Comment by tom-cosgrove-arm** [comment] 2022-11-15 06:23
@cyyyys what verification have you performed on the ALT AES implementation? While we don't run the Mbed TLS tests on target any more, we would recommend using the test vectors from the AES unit tests and verifying the ALT implementation with them - this will ensure that not just the calls to the AES hardware but also the hook-up to the ALT mechanism have been done correctly

**Comment by cyyyys** [comment] 2022-11-15 07:47
> @cyyyys what verification have you performed on the ALT AES implementation? While we don't run the Mbed TLS tests on target any more, we would recommend using the test vectors from the AES unit tests and verifying the ALT implementation with them - this will ensure that not just the calls to the AES hardware but also the hook-up to the ALT mechanism have been done correctly

We have done tests, and the AES software encryption and hardware encryption results are the same. However, a bad record mac is displayed on the server during ssl creation

**Comment by gilles-peskine-arm** [comment] 2022-11-15 18:34
I'm closing this issue because it is not clear that there is a bug in Mbed TLS, and if there is, there is not enough information to reproduce it. If you still think the problem is a bug in Mbed TLS, please provide complete instructions to reproduce the bug (preferably without needing to have your hardware!).

For general support about Mbed TLS, including further debugging tips, please use the [mailing list](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/).

**Closed by gilles-peskine-arm** 2022-11-15 18:34 UTC
Labels: component-tls
