### ISSUE TITLE
Unknown error with mbedtls after system update

### ISSUE THREAD

**Issue by alkaris2** [Mbed-TLS/mbedtls#7720] opened 2023-06-08 17:41 UTC
### Summary

I ran a system update, and after that a package was being updated for OBS Studio, and of course I'm getting these errors by mbedtls with undefined references.... I don't know what is even going on here and/or HOW this is even possible, how can you have an undefined reference if your mbedtl out the box like this??

![image](https://github.com/Mbed-TLS/mbedtls/assets/73155407/4f68f108-3524-4f34-9eb1-54cd67e66e05)

### System information

Mbed TLS version (number or commit id): 3.4.0-3
Operating system and version: Manjaro 22
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Manjaro repository
Additional environment information:

### Expected behavior

 Expected install of package to run smoothly to the end without issues after compiling.

### Actual behavior

After installing system update, an update was ran for OBS Studio, which installed this, and it required the use of mbedtls, but upon running through compilation, it throws out all these errors how it has these undefined references to all of it's own mbedtls stuff.

### Steps to reproduce

Download `obs-studio-tytan652` or just `obs-studio` and let it run through the compile process before it fails to compile due to mbedtls errors.

**Comment by tom-cosgrove-arm** [comment] 2023-06-08 18:42
Given you are updating OBS, can you ask in their forums? - this sounds like something has gone wrong at that end

Our CI builds and runs the tests many times every day without these errors, so they will relate most probably to OBS, not Mbed TLS.

**Comment by gilles-peskine-arm** [comment] 2023-06-09 08:29
Please don't post images of text: they're hard to read. Also, please post complete output, not just the last page.

Here I can just barely see at the top that `libmbedcrypto` is not found. That's a problem with the build scripts. Since they're not our build scripts, we can't help with that. You need to figure out what the problem is:

* Maybe `libmbedcrypto` should be installed but isn't? Then the problem is with what should be installing it.
* Maybe `libmbedcrypto` should be created by this build process? Then the problem is with the build script.
* Maybe `libmbedcrypto` is present but not where the script looks for it? Then the problem is with the build script, but in a different place.

I am closing this issue because it's not a problem with any of the code maintained by the Mbed TLS project.

**Closed by gilles-peskine-arm** 2023-06-09 08:29 UTC
