### ISSUE TITLE
RTMP_Connect1, TLS_Connect failed: -0x7080

### ISSUE THREAD

**Issue by jcfrosty** [Mbed-TLS/mbedtls#9861] opened 2024-12-18 18:25 UTC
### Summary
Attempting to Stream to Facebook via OBS Studio on Manjaro.

12:07:38.426: [rtmp stream: 'simple_stream'] Connecting to RTMP URL rtmps://rtmp-api.facebook.com:443/rtmp/...
12:07:38.620: RTMP_Connect1, TLS_Connect failed: -0x7080
12:07:38.621: [rtmp stream: 'simple_stream'] Connection to rtmps://rtmp-api.facebook.com:443/rtmp/ failed: -2

Evidently others have been experiencing this for a while:
https://obsproject.com/forum/threads/rtmp_connect1-tls_connect-failed-0x7080-on-facebook-live.182153/

### System information

Mbed TLS version (number or commit id): 3.6.1

Operating system and version:
Operating System: Manjaro Linux 
Kernel Version: 6.13.0-rc2-1-MANJARO (64-bit)

Configuration (if not default, please attach `mbedtls_config.h`): 
[mbedtls_config.h.txt](https://github.com/user-attachments/files/18187334/mbedtls_config.h.txt)

Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
pamac install mbedtls

Additional environment information: 
Tested on kernel version 6.11, 6.12, and 6.13rc .
Tested on SEVERAL version of OBS all the way up to the latest version.
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.1
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
Memory: 27.2 GiB of RAM
Graphics Processor: AMD Radeon 780M
Manufacturer: Framework
Product Name: Laptop 16 (AMD Ryzen 7040 Series)
### Expected behavior

Should at least connect to facebook or youtube.

### Actual behavior

Fails to connect to facebook and youtube

### Steps to reproduce

Running Manjaro, just install OBS studio. It depends on Mbedtls 3.6.1 and will pull it in. attempt to livestream to facebook.

**Comment by mpg** [comment] 2024-12-23 09:44
Hi @jcfrosty and thanks for opening an issue here.

The error code you're getting from Mbed TLS (-0x7080) is `MBEDTLS_ERR_SSL_FEATURE_UNAVAILABLE` which is not super specific: there are 42 places in the code that can return this error code.

I tried connecting to `rtmp-api.facebook.com` using one of our example programs and was able to reproduce the error:
```
% programs/ssl/ssl_client2 server_name=rtmp-api.facebook.com server_port=443 debug_level=1
build version: Mbed TLS 4.0.0 (build 67108864)

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the client cert. and key... ok (key type: RSA)
  . Setting up the SSL/TLS structure... ok
  . Connecting to tcp/rtmp-api.facebook.com/443... ok
  . Performing the SSL/TLS handshake...ssl_tls13_generic.c:1543: |1| Perform PSA-based ECDH/FFDH computation.
ssl_tls13_client.c:1943: |1| Switch to handshake keys for inbound traffic
ssl_msg.c:3296: |1| TLS handshake fragmentation not supported
ssl_msg.c:4243: |1| mbedtls_ssl_handle_message_type() returned -28800 (-0x7080)
ssl_tls13_client.c:2366: |1| mbedtls_ssl_read_record() returned -28800 (-0x7080)
 failed
  ! mbedtls_ssl_handshake returned -0x7080

Last error was: -0x7080 - SSL - The requested feature is not available
```
So, the problem appears to be that the server fragments one of the handshake messages (specifically, the CertificateRequest message, as shown by a higher debug level).

It is unfortunately a long-standing limitation that we don't support re-assembling fragmented handshake messages in TLS (as opposed to DTLS). See https://github.com/Mbed-TLS/mbedtls/issues/1840. Note that there is a community PR trying to address that (and a bit more): https://github.com/Mbed-TLS/mbedtls/pull/8981 but it requires work before it gets to a mergeable state.

**Comment by mpg** [comment] 2024-12-23 09:48
I'm closing this issue as a duplicate of https://github.com/Mbed-TLS/mbedtls/issues/1840, because from a technical perspective both are the same, but still, thank you for opening it, especially with the forum link, hopefully it will help us prioritize a fix (though I'm not making any promise as we are very busy preparing the next major version at the moment).

**Closed by mpg** 2024-12-23 09:48 UTC
Labels: enhancement
