### ISSUE TITLE
Migrate relevant Knowledgebase info from tls.mbed.org

### ISSUE THREAD

**Issue by danh-arm** [Mbed-TLS/mbedtls#3450] opened 2020-06-23 16:24 UTC
Migrate relevant Knowledgebase (KB) info from tls.mbed.org to trustedfirmware.org wiki. Also update references to KB articles in codebase.

**Comment by danh-arm** [comment] 2020-06-23 16:24
Related to #3211

**Comment by danh-arm** [comment] 2020-06-24 13:56
I expanded this task to cover all KB articles, not just the coding standards. I previously thought there were not than many references to KB articles in the codebase so we could could easily remove references to tls.mbed.org without migrating everything. I now realise there are many so it makes more sense to do this holistically than piecemeal.

**Comment by aditya-deshpande-arm** [comment] 2023-02-03 17:01
Duplicate of #4073, which has been completed.

**Closed by aditya-deshpande-arm** 2023-02-03 17:01 UTC
Labels: enhancement, historical-reviewing
