### ISSUE TITLE
Some files are getting ignored after cloning mbedtls library and commiting changes to bitbucket hosted repo

### ISSUE THREAD

**Issue by aggaddam** [Mbed-TLS/mbedtls#7421] opened 2023-04-11 05:21 UTC
### Summary

    version_features.c
    ssl_debug_helpers_generated.c
    psa_crypto_driver_wrappers.c
    error.c

The above files seem to be ignored in mbedtls/library/.gitignore, maybe when moving the files to our bitbucket repository. I am not sure why these files are added to ignore list.

### System information

Mbed TLS version (number or commit id): mbedtls-3.3.0
Operating system and version: ubuntu
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

    version_features.c
    ssl_debug_helpers_generated.c
    psa_crypto_driver_wrappers.c
    error.c
The files shouldn't be ignored

### Actual behavior

The files are ignored

### Steps to reproduce
NA

### Additional information
NA

**Comment by ronald-cron-arm** [comment] 2023-04-11 13:25
Those files are generated by the build system. They are added to .gitignore because we do not want to commit them and have to handle them when we develop commits.

**Comment by ronald-cron-arm** [comment] 2023-04-11 13:29
I am closing the issue as this is not a bug in the sense that the aforementioned files are purposely added to .gitignore. Even if the issue is closed, feel free if necessary to discuss further on the issue.

**Closed by ronald-cron-arm** 2023-04-11 13:29 UTC
