### ISSUE TITLE
mbedtls_error_add() adds path to file in compilation output 

### ISSUE THREAD

**Issue by tgiecew** [Mbed-TLS/mbedtls#9799] opened 2024-11-25 08:27 UTC
### Summary
Without MBEDTLS_TEST_HOOKS defined "file" and "line" parameters are not used. Even though it results with adding path to files where 
mbedtls_error_add() is called. 

From that reason output binaries are not the same if path to repository is different.
The other question is whether it is secure.

### System information

Mbed TLS version (number or commit id): mbedtls v 3.6.1
Operating system and version: Windows 11, Fedora 36, Ubuntu 24.04 LTS
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): clang 10.0.1
Additional environment information: 

### Expected behavior
Same output binaries after compilation in different locations. No paths to files in compilation output.

### Actual behavior
Diffs in output binaries after compilation in different locations. Paths to files in compilation output.

### Steps to reproduce
Compile.
Check compilation binaries.

**Comment by tom-daubney-arm** [comment] 2024-11-26 10:40
Hi @tgiecew , I am in the process of triaging this report and so far I am being a bit unsuccessful in reproducing the problem.

I have grabbed a fresh checkout of 3.6.1 and built it in two different locations on my systems. I made sure `MBEDTLS_TEST_HOOKS` was switched off.

I examined a few binaries, namely `pkcs7.o`, `libmbedx509.a` and `libmbedcrypto.a` with `diff` and `cmp` and I see no differences between the binaries in different locations.

I also did a `grep -a` search of the binaries to look for any file path prefixes that relate to the location of the binaries and got no results.

Could you please give a little more detail about what you did to observe these differences?

**Comment by tom-daubney-arm** [comment] 2024-12-02 10:35
Closing due to not being able to reproduce and no follow-up from OP. Feel free to re-open in the future if you want to take this further @tgiecew

**Closed by tom-daubney-arm** 2024-12-02 10:35 UTC
