### ISSUE TITLE
DTLS 1.2 retransmission optimization

### ISSUE THREAD

**Issue by sbernard31** [Mbed-TLS/mbedtls#2825] opened 2019-09-09 09:37 UTC
Using mbed v2.13.1, we faced some strange behavior about duplicate retransmission.

In this case client is an mbed client and server is a scandium server.
```
Time      Source      Destination      Info 
2.127170  client      server      Client Hello
2.287418  server      client      Hello Verify Request
2.315333  client      server      Client Hello
2.478780  server      client      Server Hello, Server Key Exchange, Server Hello Done
-----------------------------------------
No answer from client after 1s, we retransmit.
------------------------------------------
3.479602  server      client      Server Hello, Server Key Exchange, Server Hello Done
-----------------------------------------
Still no answer from client after 2s, we retransmit again.
-----------------------------------------
5.479355  server      client      Server Hello, Server Key Exchange, Server Hello Done
-----------------------------------------
The client recieved all messages but it sounds it was busy or not able to answer in time.
Now it unqueue message and answer one by one to each retransmission in a very short delay.
-----------------------------------------
5.673280  client      server      Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
5.683168  client      server      Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
5.705030  client      server      Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
-----------------------------------------
At server side we also recieve all messages and answer to each retransmission.
-----------------------------------------
5.841709  server      client      Change Cipher Spec, Encrypted Handshake Message
5.841823  server      client      Change Cipher Spec, Encrypted Handshake Message
5.863473  server      client      Change Cipher Spec, Encrypted Handshake Message
```

I think the 3 `Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message` is not a normal/optimal behavior.

This looks like https://github.com/openthread/openthread/issues/2176.
I not sure but this https://github.com/openthread/openthread/issues/2176#issuecomment-335754170 sounds to say that you didn't address the retransmission issue.
Am I right ?

More details and the complete capture is available at https://github.com/eclipse/californium/issues/1034.

**Comment by hanno-arm** [comment] 2019-09-09 09:46
Hi @sbernard31, 

thanks for your report! I agree that Mbed TLS _always_ triggers retransmission of the last outgoing flight when re-receiving the last message from the last incoming flight. If multiple instances of the list incoming flight are queued, the queue is currently not emptied after sending a retransmission, hence leading to the behavior you observed.

This is certainly not optimal, I agree - but the queue clearing hasn't been implemented so far.

To my understanding, the issue is unrelated to OpenThread 2176.

@Patater If it ever gets integrated, I suggest doing this via MPS.

Kind regards,
Hanno

**Comment by sbernard31** [comment] 2019-09-09 12:24
@hanno-arm, 
> I agree that Mbed TLS always triggers retransmission of the last outgoing flight when re-receiving the last message from the last incoming flight.

I asked myself, if this is a good point to trigger retransmission on message reception, I mean even for the first one. (Except when there is no more message excepted in FINISHED state)

**Let me explain :** 

The RFC says : 
[RFC6347, 4.2.2](https://tools.ietf.org/html/rfc6347#page-18)

> If the sequence number is less than next_receive_seq, the message MUST be discarded. 

[RFC6347, 4.2.4](https://tools.ietf.org/html/rfc6347#page-20)

> 2. The implementation reads a retransmitted flight from the peer: the
>       implementation transitions to the SENDING state, where it
>       retransmits the flight, resets the retransmit timer, and returns
>       to the WAITING state.  The rationale here is that the receipt of a
>       duplicate message is the likely result of timer expiry on the peer
>       and therefore suggests that part of one's previous flight was
>       lost.

It seems to be a bit contradictory. I mean : 
 - first one says : discard.
 - second one says : do like timer expiry (so retransmit)

I maybe missed something but my feeling is that "discard only" is enough and probably better (at least at bandwidth point of view, maybe not for latency).

I mean in this particular case, the idea would be : 
 - process the first flight `Server Hello(seq=7), Server Key Exchange(seq=8), Server Hello Done(seq=9)`
 - set next_receive_seq = 10
 - process the second flight `Server Hello(seq=7), Server Key Exchange(seq=8), Server Hello Done(seq=9)` => discard because sequence number is less than next_receive_seq
 - process the third flight `Server Hello(seq=7), Server Key Exchange(seq=8), Server Hello Done(seq=9)` => discard because sequence number is less than next_receive_seq
 - process `Change Cipher Spec(seq=10), Encrypted Handshake Message`

WDYT, do you thing it makes sense ?

**Comment by hanno-arm** [comment] 2019-09-10 10:21
@sbernard31 As you say, it's a tradeoff between latency and bandwidth: If you never trigger retransmission when receiving a retranmsission from the peer, but only after your own timer expires, you have less traffic, but the handshake potentially takes longer. It would be easy to add an option to disable peer-triggered retransmission, but as far as I know, we haven't seriously considered that.

The poor thing about how the retransmission state machine works in DTLS 1.2 is that you have to resend your whole last outgoing flight just to signal that you wish the peer to resend his flight - even if you already know that the peer has received your last flight! That's because there's no distinction between "I'm not sure you got my last flight" and "I know you got my last flight and are sending your's now, but I'm missing something". In DTLS 1.3, this is split, and there are dedicated ACK messages for the latter purpose.

**Comment by daverodgman** [comment] 2023-02-10 15:23
My understanding is that this should be considered an optimisation opportunity rather than a bug, so closing as its unlikely we will implement this soon. Please re-open if this has a significant impact for you.

**Closed by daverodgman** 2023-02-10 15:23 UTC
Labels: enhancement, component-tls, historical-reviewing
