### ISSUE TITLE
PSA Crypto SE and Storage C files include missing headers

### ISSUE THREAD

**Issue by Skptak** [Mbed-TLS/mbedtls#8518] opened 2023-11-09 19:10 UTC
### Summary
When compiling [psa_crypto_se.c](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/library/psa_crypto_storage.c#L32) or [psa_crypto_storage.c](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/library/psa_crypto_se.c#L32) with [MBEDTLS_PSA_ITS_FILE_C](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/mbedtls_config.h#L3180) undefined they attempt to include `psa/error.h` and `psa/internal_trusted_storage.h`.
```
#if defined(MBEDTLS_PSA_ITS_FILE_C)
#include "psa_crypto_its.h"
#else /* Native ITS implementation */
#include "psa/error.h"
#include "psa/internal_trusted_storage.h"
#endif
```

I do not believe these files exist? I've cloned down MBed-TLS Releases v3.2.1 through v3.5.0 and do not see these files.

 ```
 skptak@darwin22.0 [10:46] ~/repos/mbedtls
# find . -name "error.h"
./mbedtls_3_2_1/include/mbedtls/error.h
./mbedtls_3_5_0/include/mbedtls/error.h
./mbedtls_3_4_1/include/mbedtls/error.h
./mbedtls_3_3_0/include/mbedtls/error.h
skptak@darwin22.0 [10:46] ~/repos/mbedtls
# find . -name "internal_trusted_storage.h"
skptak@darwin22.0 [10:46] ~/repos/mbedtls
# find . -name "psa_crypto_se.c"
./mbedtls_3_2_1/library/psa_crypto_se.c
./mbedtls_3_5_0/library/psa_crypto_se.c
./mbedtls_3_4_1/library/psa_crypto_se.c
./mbedtls_3_3_0/library/psa_crypto_se.c
skptak@darwin22.0 [10:47] ~/repos/mbedtls
# grep --include="*.c" --include="*.h" -rni "include.*psa/error.h"
./mbedtls_3_2_1/library/psa_crypto_se.c:36:#include "psa/error.h"
./mbedtls_3_2_1/library/psa_crypto_storage.c:35:#include "psa/error.h"
./mbedtls_3_5_0/library/psa_crypto_se.c:35:#include "psa/error.h"
./mbedtls_3_5_0/library/psa_crypto_storage.c:35:#include "psa/error.h"
./mbedtls_3_4_1/library/psa_crypto_se.c:35:#include "psa/error.h"
./mbedtls_3_4_1/library/psa_crypto_storage.c:35:#include "psa/error.h"
./mbedtls_3_3_0/library/psa_crypto_se.c:36:#include "psa/error.h"
./mbedtls_3_3_0/library/psa_crypto_storage.c:35:#include "psa/error.h"
```

### System information

Mbed TLS version (number or commit id): Tested with v3.5.0 - but believe this problem could go back to v3.2.1
Operating system and version: Windows 10 build 10.0.19045
Configuration (if not default, please attach `mbedtls_config.h`): [mbedtls_config_v3.5.0.h.zip](https://github.com/Mbed-TLS/mbedtls/files/13311816/mbedtls_config_v3.5.0.h.zip)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Visual Studio 2019, MSVC Compiler 14.29.30133, WIN32 target
Additional environment information: 

### Expected behavior
When building MBed-TLS with [MBEDTLS_PSA_CRYPTO_STORAGE_C](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/mbedtls_config.h#L3168) defined and [MBEDTLS_PSA_ITS_FILE_C](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/mbedtls_config.h#L3180) undefined to successfully complete a build using a tagged release.

### Actual behavior
`fatal error C1083: Cannot open include file: 'psa/error.h': No such file or directory`

### Steps to reproduce
Build MBedTLS v3.5.0 with [MBEDTLS_PSA_CRYPTO_STORAGE_C](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/mbedtls_config.h#L3168) defined and [MBEDTLS_PSA_ITS_FILE_C](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/mbedtls_config.h#L3180) undefined

### Additional information
I'm not sure if this is an intentional outcome? Where the idea is that if using [MBEDTLS_PSA_CRYPTO_STORAGE_C](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/mbedtls_config.h#L3168) that a user should then supply an `error.h` and a `internal_trusted_storage.h` into the `psa` include directory?

I feel that if this is the expected behaviour that this should include a note or warning about it in the information for [MBEDTLS_PSA_CRYPTO_STORAGE_C](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/mbedtls_config.h#L3168) then. Especially as there options that include warnings like this, such as the [MBEDTLS_PKCS12_C](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/mbedtls_config.h#L3099) option

**Comment by tom-cosgrove-arm** [comment] 2023-11-09 19:18
In `mbedtls_config.h` it says

```
/**
 * \def MBEDTLS_PSA_CRYPTO_STORAGE_C
 *
 * Enable the Platform Security Architecture persistent key storage.
 *
 * Module:  library/psa_crypto_storage.c
 *
 * Requires: MBEDTLS_PSA_CRYPTO_C,
 *           either MBEDTLS_PSA_ITS_FILE_C or a native implementation of
 *           the PSA ITS interface
 */
#define MBEDTLS_PSA_CRYPTO_STORAGE_C
```

If you don't want `MBEDTLS_PSA_ITS_FILE_C` which is "the emulation of the Platform Security Architecture Internal Trusted Storage (PSA ITS) over files" (from the following entry), then *_you_* must provide "a native implementation of the PSA ITS interface".

Mbed TLS does not provide a native implementation of the PSA ITS interface, only an emulation over files.

**Comment by Skptak** [comment] 2023-11-09 19:40
> then you must provide "a native implementation of the PSA ITS interface".
And I totally get that, I just felt it was odd that this includes `psa/error.h` and `psa/internal_trusted_storage.h`? Since this made me think these were existing files in the repo.

I just felt that it should include a config option like how is done with the [MBEDTLS_CONFIG_FILEs](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.0/include/mbedtls/build_info.h#L88). That or the config option should mention files with this exact path and name are needed?

But understand if this is considered a non-issue, just wanted to bring it up when I hit it.

**Comment by gilles-peskine-arm** [comment] 2023-11-09 20:35
This is the intended behavior. Mbed TLS requires an implementation of the PSA ITS interface to implement persistent keys in the PSA Crypto API. Mbed TLS includes one implementation of this interface: `PSA_ITS_FILE_C`. If you disable that, you need to provide an alternative implementation. An implementation of PSA ITS must provide headers `psa/error.h` and `psa/internal_trusted_storage.h`, and linkable functions `psa_its_get_info`, `psa_its_get`, `psa_its_set` and `psa_its_remove`.

The PSA ITS interface is a system interface, like stdio or pthread. Mbed TLS doesn't provide `psa/internal_trusted_storage.h` any more than it provides `stdio.h` or `pthread.h`.

> Expected behavior
>
> When building MBed-TLS with MBEDTLS_PSA_CRYPTO_STORAGE_C defined and MBEDTLS_PSA_ITS_FILE_C undefined to successfully complete a build using a tagged release.

This does work if your platform provides a PSA storage interface, for example on TF-M. If you're on a platform that provides stdio but not PSA ITS, such as POSIX or Windows or any other hosted C implementation, just keep `MBEDTLS_PSA_ITS_FILE_C` enabled. I don't quite understand why you want to disable it, since you're apparently building on Windows and for Windows?

I'm closing this issue because the behavior is as desired. I think the documentation is ok as it is, but if you think it's unclear, please submit a patch in a pull request.

**Closed by gilles-peskine-arm** 2023-11-09 20:35 UTC
