### ISSUE TITLE
Code Size: Module exclusion check: libmbedcrypto

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [Mbed-TLS/mbedtls#7372] opened 2023-03-30 12:34 UTC
For each of the modules in libmbedcrypto, check that if it can be configured out by a configuration option, that all of the appropriate modules (C source files) are completely d out

For each module that isn't, raise a PR to add the `#if defined()`...`#endif`

DoD: If a module in libmbedcrypto  is configured out, none of its code appears in the linked library (`.a` file)

Note: It is expected that (if any) at most one or two modules (beyond the known one, Everest) will be found that need modification, hence this is considered size S

**Comment by gilles-peskine-arm** [comment] 2023-04-08 14:03
The one case I'm aware of is `constant_time.c`: many utility functions are systematically enabled.

**Comment by tom-daubney-arm** [comment] 2023-04-24 10:41
Current update on findings. So far the following modules (listed below) are all guarded correctly and can be easily switched off. When they are switched off their corresponding `.o` files have zero size when measured using the `size` binutil. Note that the vast majority of these modules are archived into `libmbedcrypto.a` when compiled however I have also checked some modules that are archived into `libmbedtls.a` and `libmbedx509.a` and they are included in this list. This list also documents the relevant config options for each module that can be used to switch them on or off.

| Module Name                   | Config Options(s)                               |
| ----------------------------- | ----------------------------------------------- |
| aes.c                         | MBEDTLS_AES_C                                   |
| aria.c                        | MBEDTLS_ARIA_C                                  |
| base64.c                      | MBEDTLS_BASE64_C                                |
| camellia.c                    | MBEDTLS_CAMELLIA_C                              |
| ccm.c                         | MBEDTLS_CCM_C                                   |
| chacha20.c                    | MBEDTLS_CHACHA20_C                              |
| chachapoly.c                  | MBEDTLS_CHACHAPOLY_C                            |
| cmac.c                        | MBEDTLS_CMAC_C                                  |
| ctr_drbg.c                    | MBEDTLS_CTR_DRBG_C                              |
| debug.c                       | MBEDTLS_DEBUG_C                                 |
| des.c                         | MBEDTLS_DES_C                                   |
| ecjpake.c                     | MBEDTLS_ECJPAKE_C                               |
| error.c                       | MBEDTLS_ERROR_C || MBEDTLS_ERROR_STRERROR_DUMMY |
| gcm.c                         | MBEDTLS_GCM_C                                   |
| hkdf.c                        | MBEDTLS_HKDF_C                                  |
| lmots.c                       | MBEDTLS_LMS_C                                   |
| lms.c                         | MBEDTLS_LMS_C                                   |
| md5.c                         | MBEDTLS_MD5_C                                   |
| memory_buffer_alloc.c         | MBEDTLS_MEMORY_BUFFER_ALLOC_C                   |
| nist_kw.c                     | MBEDTLS_NIST_KW_C                               |
| padlock.c                     | MBEDTLS_PADLOCK_C                               |
| pem.c                         | MBEDTLS_PEM_PARSE_C || MBEDTLS_PEM_WRITE_C      |
| pkcs12.c                      | MBEDTLS_PKCS12_C                                |
| pkcs5.c                       | MBEDTLS_PKCS5_C                                 |
| poly1305.c                    | MBEDTLS_POLY1305_C                              |
| psa_crypto_se.c               | MBEDTLS_PSA_CRYPTO_SE_C                         |
| psa_crypto_storage.c          | MBEDTLS_PSA_CRYPTO_STORAGE_C                    |
| ripemd160.c                   | MBEDTLS_RIPEMD160_C                             |
| sha1.c                        | MBEDTLS_SHA1_C                                  |
| sha512.c                      | MBEDTLS_SHA512_C || MBEDTLS_SHA384_C            |
| ssl_cache.c                   | MBEDTLS_SSL_CACHE_C                             |
| ssl_ciphersuites.c            | MBEDTLS_SSL_TLS_C                               |
| ssl_client.c                  | MBEDTLS_SSL_CLI_C                               |
| ssl_cookie.c                  | MBEDTLS_SSL_COOKIE_C                            |
| ssl_debug_helpers_generated.c | MBEDTLS_DEBUG_C                                 |
| ssl_msg.c                     | MBEDTLS_SSL_TLS_C                               |
| ssl_ticket.c                  | MBEDTLS_SSL_TICKET_C                            |
| ssl_tls12_client.c            | MBEDTLS_SSL_CLI_C && MBEDTLS_SSL_PROTO_TLS1_2   |
| ssl_tls12_server.c            | MBEDTLS_SSL_SRV_C && MBEDTLS_SSL_PROTO_TLS1_2   |
| ssl_tls13_client.c            | MBEDTLS_SSL_CLI_C && MBEDTLS_SSL_PROTO_TLS1_3   |
| ssl_tls13_generic.c           | MBEDTLS_SSL_TLS_C && MBEDTLS_SSL_PROTO_TLS1_3   |
| ssl_tls13_keys.c              | MBEDTLS_SSL_PROTO_TLS1_3                        |
| ssl_tls13_server.c            | MBEDTLS_SSL_SRV_C && MBEDTLS_SSL_PROTO_TLS1_3   |
| ssl_tls.c                     | MBEDTLS_SSL_TLS_C                               |
| threading.c                   | MBEDTLS_THREADING_C                             |
| timing.c                      | MBEDTLS_TIMING_C                                |
| version.c                     | MBEDTLS_VERSION_C                               |
| version_features.c            | MBEDTLS_VERSION_FEATURES                        |
| x509_create.c                 | MBEDTLS_X509_CREATE_C                           |
| x509write_crt.c               | MBEDTLS_X509_CRT_WRITE_C                        |
| x509write_csr.c               | MBEDTLS_X509_CSR_WRITE_C                        |

For the remaining modules, further investigation is required, which I am currently doing. This is because they are either not straight forward to switch off, or because they are not guarded in the usual way. I will post another comment once the further investigation has happened.

**Comment by tom-daubney-arm** [comment] 2023-04-24 16:03
Further to the previous comment I have now established that the following modules also work as intended:
| Module Name | Config Option(s) |
| ---------------------------- | ------------------------ |
| aesni.c                      | MBEDTLS_AESNI_C          |
| bignum.c                     | MBEDTLS_BIGNUM_C         |
| bignum_core.c                | MBEDTLS_BIGNUM_C         |
| bignum_mod.c                 | MBEDTLS_BIGNUM_C         |
| bignum_mod_raw.c             | MBEDTLS_BIGNUM_C         |
| cipher.c                     | MBEDTLS_CIPHER_C         |
| cipher_wrap.c                | MBEDTLS_CIPHER_C         |
| dhm.c                        | MBEDTLS_DHM_C            |
| ecdh.c                       | MBEDTLS_ECDH_C           |
| ecdsa.c                      | MBEDTLS_ECDSA_C          |
| ecp.c                        | MBEDTLS_ECP_C            |
| ecp_curves.c                 | MBEDTLS_ECP_C            |
| psa_crypto_aead.c            | MBEDTLS_PSA_CRYPTO_C     |
| psa_crypto.c                 | MBEDTLS_PSA_CRYPTO_C     |
| psa_crypto_cipher.c          | MBEDTLS_PSA_CRYPTO_C     |
| psa_crypto_ecp.c             | MBEDTLS_PSA_CRYPTO_C     |
| psa_crypto_hash.c            | MBEDTLS_PSA_CRYPTO_C     |
| psa_crypto_mac.c             | MBEDTLS_PSA_CRYPTO_C     |
| psa_crypto_pake.c            | MBEDTLS_PSA_CRYPTO_C     |
| psa_crypto_rsa.c             | MBEDTLS_PSA_CRYPTO_C     |
| psa_crypto_slot_management.c | MBEDTLS_PSA_CRYPTO_C     |
| psa_its_file.c               | MBEDTLS_PSA_ITS_FILE_C   |
| psa_util.c                   | MBEDTLS_PSA_CRYPTO_C     |
| rsa_alt_helpers.c            | MBEDTLS_RSA_C            |
| rsa.c                        | MBEDTLS_RSA_C            |
| x509.c                       | MBEDTLS_X509_USE_C       |
| x509_crl.c                   | MBEDTLS_X509_CRL_PARSE_C |
| x509_crt.c                   | MBEDTLS_X509_CRT_PARSE_C |
| x509_csr.c                   | MBEDTLS_X509_CSR_PARSE_C |

**Comment by tom-daubney-arm** [comment] 2023-04-24 16:47
There are three classes of outstanding modules left to look at in this issue. The first are modules that I am yet to be able to turn off. These are:

| Module Name | Config Option(s) |
| --- | --- |
| asn1parse.c | MBEDTLS_ASN1_PARSE_C |
| asn1write.c | MBEDTLS_ASN1_WRITE_C |
| md.c | MBEDTLS_MD_LIGHT |
|oid.c | MBEDTLS_OID_C |

The second class of modules are modules that are not guarded in the normal way and so I have not been able to switch them off yet:

| Module Name |
| --- |
| constant_time.c |
| hash_info.c |
| platform_util.c |

The third class of modules are ones that are guarded in the correct way, but when they are switched off their code size does not fully reduce to zero. For each of the following modules they all reduce to the following code size when switched off:

| Text | Data |
| --- | --- |
| 66 B | 8 B |

These modules are:

| Module Name | Config Option(s) |
| --- | --- |
| entropy.c | MBEDTLS_ENTROPY_C |
| entropy_poll.c | MBEDTLS_ENTROPY_C |
| hmac_drbg.c | MBEDTLS_HMAC_DRBG_C |
| mps_reader.c | MBEDTLS_SSL_PROTO_TLS1_3 |
| mps_trace.c | MBEDTLS_SSL_PROTO_TLS1_3 |
| sha256.c | MBEDTLS_SHA256_C \|\| MBEDTLS_SHA224_C |

**Comment by gilles-peskine-arm** [comment] 2023-04-24 18:39
For a real-world ASN1 and OID, try a configuration with no asymmetric crypto, e.g. `configs/config-ccm-psk-tls1_2.h`.

Almost everything needs MD light except symmetric ciphers. TLS always needs MD light. I would expect `hash_info` to be empty iff MD light is disabled.

But I don't understand what the difficulty is here: why can't you just look at an empty `mbedtls_config.h`?

**Comment by tom-daubney-arm** [comment] 2023-04-25 10:25
Thanks for the suggestion @gilles-peskine-arm. It had not occured to me to build with an empty config file. I have done that now and have the following final results:

Everything reduces to 0 code size with the following 3 exceptions:

| Module Name | text | data | bss | dec | hex |
| --- | --- | --- | --- | --- | --- |
| constant_time.c | 396 | 0 | 0 | 396 | 18c |
| hash_info.c | 516 | 0 | 0 | 516 | 204 |
| platform_util.c | 790 | 0 | 0 | 316 |

So, the question is now: Do we call this investigation complete and close the issue? Or do I spend time looking through the aforemetioned three modules and try to look for potential code size wins in there? @tom-cosgrove-arm please weigh in! Thanks

**Comment by gilles-peskine-arm** [comment] 2023-04-25 12:22
`constant_time` and `platform_util` have always-on functions because each function has its own set of callers, and many functions are needed by so many different modules that most realistic builds would require them anyway. That being said, `platform_util` is a lot bigger than I'd expected: I thought `zeroize` would be the only always-on thing there.

`hash_info` is [being removed](https://github.com/Mbed-TLS/mbedtls/pull/7349).

**Comment by tom-cosgrove-arm** [comment] 2023-04-25 17:14
For `constant_time.c` the always-on functions are

```
00000001 T mbedtls_ct_memcmp
00000001 T mbedtls_ct_size_bool_eq
00000001 T mbedtls_ct_uint_if
00000001 T mbedtls_ct_uint_mask
```

`mbedtls_ct_memcmp()` is a low-level function that is reasonably needed for pretty much any crypto (e.g. verifying HMAC). It's 28 bytes long.

`mbedtls_ct_size_bool_eq()` is required by bignum, but also within `constant_time.c` by `mbedtls_ct_memcpy_if_eq()`, which is under `MBEDTLS_SSL_SOME_SUITES_USE_MAC`.  It's only 10 bytes, though.

`mbedtls_ct_uint_if()` is only used within `constant_time.c`, by functions which are under config options, so is unnecessary. However, it is along only 10.

`mbedtls_ct_uint_mask()` is used within `constant_time.c` and `ssl_tls12_server.c`. It also is 10 bytes long.

So I don't think there is anything significant to worry about from `constant_time.c`.

**Comment by tom-daubney-arm** [comment] 2023-04-26 16:58
For ```platform_util.c``` the always-on functions are:

| Function Name | Size in B | Usage |
| --- | --- | --- |
| mbedtls_platform_zeroize | 16 | Securely zeroize a buffer |
| mbedtls_xor| 40 | Perform a fast block XOR operation |
| mbedtls_get_unaligned_uint16 | 4 | Reading an unaligned 16-bit int |
| mbedtls_put_unaligned_uint16 | 4 | Writing an unaligned 16-bit int |
| mbedtls_get_unaligned_uint32 | 4 | Reading an unaligned 32-bit int |
| mbedtls_put_unaligned_uint32 | 4 | Writing an unaligned 32-bit int |
| mbedtls_get_unaligned_uint32 | 8 | Reading an unaligned 64-bit int |
| mbedtls_put_unaligned_uint32 | 6 | Writing an unaligned 64-bit int |

So in a similar vein to `constant_time.c` I don't think there is much saving to be had here. I think that maybe we could guard `mbedtls_xor` but it hardly seems worth it given the recent increase in code size due to bignum (~2.5kB).

As such I am closing the issue.

**Closed** 2023-04-26 17:00 UTC
Labels: size-s, size-optimisation
