### ISSUE TITLE
mbedtls_mpi_is_prime doesn't always work if there are leading zeros

### ISSUE THREAD

**Issue by jethrogb** [Mbed-TLS/mbedtls#6956] opened 2023-01-23 16:06 UTC
The following test program:
```c
#include <stdio.h>
#include <mbedtls/bignum.h>

void test(void* f_rng) {
    unsigned char a_buf[] = {0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff};
    unsigned char b_buf[] = {0, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff};
    mbedtls_mpi a, b;
    mbedtls_mpi_init(&a);
    mbedtls_mpi_init(&b);
    mbedtls_mpi_read_binary(&a, a_buf, sizeof(a_buf));
    mbedtls_mpi_read_binary(&b, b_buf, sizeof(b_buf));
    printf("%d\n", mbedtls_mpi_is_prime(&a, f_rng, NULL));
    printf("%d\n", mbedtls_mpi_is_prime(&b, f_rng, NULL));
    mbedtls_mpi_shrink(&b, 0);
    printf("%d\n", mbedtls_mpi_is_prime(&b, f_rng, NULL));
}
```
Outputs:
```
0
-14
0
```
I expected the output to be:
```
0
0
0
```

**Comment by gilles-peskine-arm** [comment] 2023-01-23 20:38
Duplicate of https://github.com/Mbed-TLS/mbedtls/issues/5902

**Closed by gilles-peskine-arm** 2023-01-23 20:38 UTC
