### ISSUE TITLE
CMAC Alternate Implementation

### ISSUE THREAD

**Issue by shreyt09** [Mbed-TLS/mbedtls#1885] opened 2018-07-25 20:18 UTC
### Description
- Type: Bug

Memory leak

For the CMAC implementation, there is no free function. This is an issue when
providing alternate implementations. If the alternate struct contains pointers that are dynamically
allocated then they will never be freed.

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.11.0
Configuration: Attached my config file. For some reason, Git does not let me attach .h files so the extension has been changed to .txt.

[config.txt](https://github.com/ARMmbed/mbedtls/files/2228999/config.txt)

Potential Solution: Provide a free function for the CMAC implementation and change mbedtls_cipher_free function in cipher.c to call the CMAC free function.
 
In cmac.c

```
void mbedtls_cipher_cmac_free( mbedtls_cipher_context_t *ctx )
{
   mbedtls_zeroize( ctx->cmac_ctx, sizeof( mbedtls_cmac_context_t ) );
   mbedtls_free( ctx->cmac_ctx );
}
```

In cmac.h

```
void mbedtls_cipher_cmac_free( mbedtls_cipher_context_t *ctx );
```

In cipher.c change mbedtls_cipher_free to be

```
void mbedtls_cipher_free( mbedtls_cipher_context_t *ctx )
{
    if( ctx == NULL )
        return;

#if defined(MBEDTLS_CMAC_C)
    if( ctx->cmac_ctx )
       mbedtls_cipher_cmac_free( ctx );
#endif

    if( ctx->cipher_ctx )
        ctx->cipher_info->base->ctx_free_func( ctx->cipher_ctx );

    mbedtls_zeroize( ctx, sizeof(mbedtls_cipher_context_t) );
}
```

**Comment by RonEld** [comment] 2018-07-26 07:41
@shreyt09 Thank you for reporting this!

IMHO, this is an enhancement, and not a bug, as the memory leak is not in the Mbed TLS code base, but in an alternative implementation. However, I agree with you that this functionality should be added.
Would you mind accepting our CLA and contributing your suggestion as a PR?

**Comment by danh-arm** [comment] 2020-04-02 10:47
Hi @shreyt09.

I'm sorry this issue you reported hasn't gone anywhere. In case you were interested in submitting a PR for this and were put off by the CLA, I'd just like to let you know our [contributing guidelines](https://github.com/ARMmbed/mbedtls/blob/development/CONTRIBUTING.md#making-a-contribution) have changed and a CLA is no longer required. We just need a "Signed-off-by:" to indicate acceptance of the DCO.

Regards

Dan.

**Comment by daverodgman** [comment] 2022-05-13 11:54
Note (as I'm removing the CLA requested label): we can't accept the above code as it didn't receive CLA sign-off, so any fix of this bug would need us to re-implement without basing it on the supplied code.

**Comment by tom-cosgrove-arm** [comment] 2023-01-13 12:22
Closing this as the `ALT` interface is not going to get any enhancements - this kind of thing is handled by PSA drivers now. At some point in the future the `ALT` interfaces will be deprecated then eventually removed.

**Closed by tom-cosgrove-arm** 2023-01-13 12:22 UTC
Labels: enhancement, component-crypto, good-first-issue, historical-reviewing
