### ISSUE TITLE
there is no implementation for ecc decrypt, how to decrypt ecc by mbedtls

### ISSUE THREAD

**Issue by ysw199906** [Mbed-TLS/mbedtls#9487] opened 2024-08-16 02:08 UTC
https://github.com/Mbed-TLS/mbedtls/blob/2ca6c285a0dd3f33982dd57299012dacab1ff206/library/pk_wrap.c#L1134

**Comment by tom-daubney-arm** [comment] 2024-08-22 08:57
Hi,

thanks for reaching out. I am not sure if this will fully answer your query but try looking at the function `psa_asymmetric_decrypt` in `psa_crypto.c`.

I am closing this issue since it is not a bug or an enhancement request but rather a support request. Support requests are directed towards our mailing list which can be reached at mbed-tls@lists.trustedfirmware.org. If you need further help, please send an email there. It is actively monitored.

**Closed by tom-daubney-arm** 2024-08-22 08:57 UTC

**Comment by ysw199906** [comment] 2024-08-22 09:34
> Hi,
> 
> thanks for reaching out. I am not sure if this will fully answer your query but try looking at the function `psa_asymmetric_decrypt` in `psa_crypto.c`.
> 
> I am closing this issue since it is not a bug or an enhancement request but rather a support request. Support requests are directed towards our mailing list which can be reached at [mbed-tls@lists.trustedfirmware.org](mailto:mbed-tls@lists.trustedfirmware.org). If you need further help, please send an email there. It is actively monitored.

thank you , psa_asymmetric_decrypt, this function just for rsa.I will contract with email.

**Comment by gilles-peskine-arm** [comment] 2024-08-22 13:48
What ECC-based encryption mechanism do you want? There are several, but none are very popular.

If you just want some way to set up encrypted communication using elliptic-curve keys, I recommend that you pick an existing protocol if possible. If no existing protocol meets your requirements, then I recommend using [ECIES](https://en.wikipedia.org/wiki/Integrated_Encryption_Scheme). Mbed TLS doesn't have an interface called ECIES, but you can still use it because ECIES is basically ECDH plus symmetric encryption. Use `mbedtls_pk_parse_key` and `mbedtls_pk_parse_public_key` to parse a key, then `mbedtls_pk_import_into_psa` to obtain a PSA key id for the algorithm `PSA_ALG_ECDH` and the usage `PSA_KEY_USAGE_DERIVE`. Use `psa_raw_key_agreement` to perform the ECC calculation. [I've been wanting to write a sample program for that for a while](https://github.com/Mbed-TLS/mbedtls/issues/5780).
