### ISSUE TITLE
Backport CMake package feature into 2.28

### ISSUE THREAD

**Issue by pauloacmartinez** [Mbed-TLS/mbedtls#5675] opened 2022-03-30 20:46 UTC
### Suggested enhancement

Merge #4259 into the [mbedtls-2.28](https://github.com/Mbed-TLS/mbedtls/tree/mbedtls-2.28) branch

### Justification

This feature makes the integration of Mbed TLS straightforward into other CMake projects thus making it desirable for the long-term branch. Without this, projects depending on this have to write their own CMake build or maintain a fork of this project.

**Comment by paul-elliott-arm** [comment] 2022-04-01 12:11
This would probably benefit from the backport of https://github.com/Mbed-TLS/mbedtls/pull/5283 as well.

**Comment by gilles-peskine-arm** [comment] 2022-04-04 10:03
In LTS branches, we try not to break backward compatibility with development tools. Although 2.2x didn't have a formal compatibility list, we're using the timelines in https://github.com/Mbed-TLS/mbedtls/issues/2896#issuecomment-603471273 as a guideline, which means that **Mbed TLS 2.28 LTS should remain compatible with CMake 2.8.12.2**. Obviously that only goes for already existing features: it's ok if what currently works in Mbed TLS 2.28 keeps working with CMake 2.8.12.2, but the package feature requires a more recent version.

**Comment by paul-elliott-arm** [comment] 2022-04-06 12:11
https://github.com/Kitware/CMake/releases/tag/v2.8.12.2

**Comment by paul-elliott-arm** [comment] 2022-04-27 16:25
Hi @pauloacmartinez - I did the backports, however this (as it stands) does not work with our minimum supported version of 2.8.12, which cannot be changed for LTS branches, obviously.

The problem is that it uses the EXPORT argument to export(), which was introduced in 3.0. 

It may potentially be possible to work around with the use of export(TARGETS) (the documentation suggests it doesn't do anything that can't be done through the older method), however this is not something that I am really wanting to put the time into right now.

The backported PR is here : #5782. If you feel like fixing this so it works with 2.8.12, then this might get resolved, otherwise it is unlikely to happen in the lifespan of the 2.28 branch I am afraid.

**Comment by daverodgman** [comment] 2023-03-31 09:45
Closing; we don't plan to port this to 2.28

**Closed by daverodgman** 2023-03-31 09:45 UTC
Labels: enhancement, help-wanted, size-s, historical-reviewing
