### ISSUE TITLE
Review tests of functions that had duplicated arguments

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6371] opened 2022-09-26 21:09 UTC
Some bignum tests have been merged with duplicated test arguments for 32-bit vs 64-bit systems. This makes both the code and the data set more complex and harder to review. See https://github.com/Mbed-TLS/mbedtls/pull/6083#discussion_r961608645, https://github.com/Mbed-TLS/mbedtls/pull/6083#discussion_r971135032, https://github.com/Mbed-TLS/mbedtls/pull/6083#pullrequestreview-1107671095

As a consequence, in my review of #6083, I have not fully verified the correctness and coverage of the following test functions:

* `mpi_core_add_if`
* `mpi_core_sub`
* `mpi_core_mla`
* `mpi_core_montmul`

(List to be expanded if other pull requests are merged with the same approach before https://github.com/Mbed-TLS/mbedtls/issues/6370 is done.)

The goal of this task is to review those test functions and the test data once they have been [converted to a style without such argument pairs](https://github.com/Mbed-TLS/mbedtls/issues/6370). No new code is expected if the review is satisfactory.

**Comment by yanesca** [comment] 2022-11-01 12:46
The tests in question have been refactored to be generated by the python framework, which already makes them easier to review and #6370 is not a prerequisite anymore.

Use #6399 to start the review:
- Add a comment explaining what is happening
- Review it focusing on the test cases and coverage
- Raise a new PR addressing the issues found
- The first/main reviewer of the new PR should start their review at #6399

**Comment by minosgalanakis** [comment] 2022-11-29 15:16
Since #6632  all test cases are by default testing the combinations of the following inputs. The have been reviewed as acceptablely representative values and edge cases in most cases. 

~~~~~~~
INPUTS_DEFAULT = [
        "0", "1", # corner cases
        "2", "3", # small primes
        "4",      # non-prime even
        "38",     # small random
        SAFE_PRIME_192_BIT_SEED_1,  # prime
        RANDOM_192_BIT_SEED_2_NO1,  # not a prime
        RANDOM_192_BIT_SEED_2_NO2,  # not a prime
        SAFE_PRIME_1024_BIT_SEED_3, # prime
        RANDOM_1024_BIT_SEED_4_NO1, # not a prime
        RANDOM_1024_BIT_SEED_4_NO3, # not a prime
        RANDOM_1024_BIT_SEED_4_NO2, # largest (not a prime)
        ]

MODULI_DEFAULT = [
        "53", # safe prime
        "45", # non-prime
        SAFE_PRIME_192_BIT_SEED_1,  # safe prime
        RANDOM_192_BIT_SEED_2_NO4,  # not a prime
        SAFE_PRIME_1024_BIT_SEED_3, # safe prime
        RANDOM_1024_BIT_SEED_4_NO5, # not a prime
        ]
~~~~~~
When a test is set-up as archsplit, duplicate tests cases are generated for  `MBEDTLS_HAVE_INT32` and `MBEDTLS_HAVE_INT64`
dependencies.

The following methods are using this approach and having a consistent and satisfying our coverage requirements:
-  `mpi_core_sub_int`
-  `mpi_core_add_if`

**Comment by yanesca** [comment] 2022-11-30 12:31
> Should we rewrite the tests and the method in the currrent archsplit design to improve maintanability?

Yes we should, we have already got a task tracking the followup to this task, I have made a comment to clarify that we should use the new python classes for this https://github.com/Mbed-TLS/mbedtls/issues/6370#issuecomment-1332061764.

**Comment by gabor-mezei-arm** [comment] 2022-12-01 09:55
Using multiple input values for the same purpose only for handle the different limb sizes make the test harder to read and understand. These test functions should be changed to use one parameter for an input value. 

##### `mpi_core_add_and_add_if`
* Using the default input values which not containing a big value enough to test the overflow. The coverage would be satisfactory if the input values are extended with `LIMB_MAX_SIZE`.

##### `mpi_core_sub`
```
void mpi_core_sub( char * input_A, char * input_B,
                   char * input_X4, char * input_X8,
                   int carry )
```
* The coverage is satisfactory as they using the default input values.
* Should be use one parameter for `input_X`.
* The generator class should be updated to use `arch_split` for input style.

##### `mpi_core_mla`
```
void mpi_core_mla( char * input_A, char * input_B, char * input_S,
                   char * input_X4, char * input_cy4,
                   char * input_X8, char * input_cy8 )
```
* Using a special set of input values which not containing a big value enough to test the overflow. Using the default input values with the extension of `LIMB_MAX_SIZE` would be satisfactory.
* Should use one parameter for `input_X` and `input_cy`.
* The generator class should be updated to use `arch_split` for input style.
* The description of the test case should be changed to not using the `0x` prefix for the numbers to be confirm with the other tests.

##### `mpi_core_montmul`
```
void mpi_core_mla( char * input_A, char * input_B, char * input_S,
                   char * input_X4, char * input_cy4,
                   char * input_X8, char * input_cy8 )
```
* Using pregenerated random input values which provides a satisfactory coverage.
* Should use one parameter for `input_X` and `input_cy`.
* The generator class should be updated to use `arch_split` for input style.

**Comment by minosgalanakis** [comment] 2022-12-01 17:16
With regards to `mpi_core_montmul` the current testing implementation not using the standard inputs for A, B and moduli N, but rather using a combination of some hardcoded parameters, and a set of randonly generated ones. While this results in greater converage, it may be harder to reproduce a failure, and adds unnessary complexity to the code.

It also is not testing for `Input_A->limbs != input_B->limbs`. ( Not testing it in the hardcoded test cases, but it may end up getting tested in the randomly generated ones )

With regards to Aliasing it is testing the following which is fully satistying our coverage requirements. 

- `X --> A`
- `X --> N`
- `A <--> B`
- `X --> B`

`mpi_core_mla` is following the same design logic as monmull, and tests with a limitted set of inputs/moduli, and then a wider range of randomly generated ones.

It also introduces a new parameter scalar instead of moduli

~~~~~~
    input_scalars = [
        "0", "3", "fe", "ff", "ffff", "10000", "ffffffff", "100000000",
        "7f7f7f7f7f7f7f7f", "8000000000000000", "fffffffffffffffe"
    ] 
~~~~~~

With regards to aliasing it is only checking for:
`A->limbs==B->limbs --> X`

While in the documentation it is stated as

~~~~~
 * \p X may be aliased to \p A (when \p X_limbs == \p A_limbs), but may not
 * otherwise overlap.
~~~~~

TDB: Weather we should update the tests or the documentation. What is the valid behaviour?

Workitem

For both of the above a task should be raised wiith the following asks:

* Refactor the python code to utilise the standard inputs as the rest of the methods.
* Expand the standard inputs and moduli with extras covering edge cases specific to multiplication, that are not covered by the standard inputs. This can be done in the subclasses or in the common files for everyone to use those new values.
* Add the extra scallar input for the `mpi_core_mla`
* Calculate all possible combinations of the above.
* When calculating the combination, A and B should be treated as different inputs rather than a pair, and as such allow combinations with different limb sizes. 
* The is_valid method should filter `A->limbs != N->limbs` cases. 
* Append some randomly generated test cases, with inputs that are not covered by the fixed ones. 
* Refactor the input parameters to follow the standard notation and use arch_split.

**Comment by minosgalanakis** [comment] 2022-12-05 17:05
Appropriate follow-up tasks have been created and linked with the bignum tech debt epic. Closing as complete for the scope of coverage investigation this task serves.

**Closed by minosgalanakis** 2022-12-05 17:05 UTC
Labels: enhancement, component-crypto, size-s
