### ISSUE TITLE
trusted cert in chain is not validated itself.

### ISSUE THREAD

**Issue by dirkx** [Mbed-TLS/mbedtls#3519] opened 2020-07-27 07:22 UTC
Type: bug

During a mbedtls_x509_crt_verify() - the chain of signatures is checked up to, but _excluding_ the final certifcate in the trusted list.

Priority: Minor

**OS**  
all
**mbed TLS build:**  
all

**Expected behavior**   

Most X.509 certificates also check the signature (and other sundry) of the trusted certificate in the chain.

**Actual behavior**  

All are checked - except the trusted one.

**Steps to reproduce**  

Create a self signed cert and sign a leaf cert.
Verify that mbedtls_x509_crt_verify() gives the ok.

With a hex editor/VI change the first character of the CN - of the issuer; thus invalidating the signature/digest

Verify that mbedtls_x509_crt_verify() gives the ok.

Expected - to fail.

*Why needed*

This was found in a production case - where a third party used the changed Issuer string, which was shown in a UI, for the start of a highly technical "social" engineering attac.

**Comment by gilles-peskine-arm** [comment] 2020-07-30 19:19
Hi Dirk-Willem,

Are you modifying the trusted CA certificate, or the leaf certificate signed by the CA?

If changing the issuer CN in the leaf certificate doesn't invalidate it, that's a grave bug. But I can't reproduce this.

If changing the issuer CN in the trusted CA certificate doesn't invalidate it, that's expected. The issuer in a trusted certificate is irrelevant. For the verification, the subject name of the CA has to match the issuer name of the leaf, and the leaf's signature has to be valid for the CA's public key. The issuer of the CA certificate doesn't come into play.

The signature of a trusted root certificate is not verified. This, again, is expected. The verification is not useful since anyone who can modify the trusted root can substitute their own certificate, signed by a key under their control. And the verification would often fail in practice, because the root certificate may be signed by an obsolete algorithm, or by another CA that is not known. To give an example, this GitHub page is served to me with a certificate chain rooted in a self-signed DigiCert root CA emitted in 2006 with a signature made using SHA-1 and RSA. A browser would not accept SHA-1 signatures, but this is a trusted certificate, so the signature is irrelevant. The signature chain from the root CA to the production CA, then from the production CA to GitHub, uses SHA-256 at both steps.

Could you explain the mechanism of the social engineering attack? It's not clear to me how Mbed TLS could help here. The issuer of a trusted root is irrelevant and should not be shown in a GUI outside of an exhaustive list of all certificate fields. What matters in the root certificate is its public key and its subject name.

Since the motivating case involves social engineering, it's better if every equivalent software behaves in the same way. Do other X.509 libraries behave differently in your scenario?

**Comment by yanesca** [comment] 2022-05-13 12:18
@gilles-peskine-arm I agree with your assessment and I can't see how verifying the trusted certificate would help here either.

Because of this, I am closing this issue down.

@dirkx please feel free to reopen if you can share the details of the attack.

**Closed by yanesca** 2022-05-13 12:18 UTC
Labels: component-x509, needs-info
