### ISSUE TITLE
PSA crypto - global variable - no concurrency

### ISSUE THREAD

**Issue by lhuang04** [Mbed-TLS/mbedtls#7946] opened 2023-07-18 14:15 UTC
### Suggested enhancement
Per suggestion from @paul-elliott-arm, open a separate issue here to track the ones discussed in [global variable issue in PSA crypto](https://github.com/ARM-software/psa-api/issues/77).

- There may be no concurrency, for example, there is only [one slot for a volatile key](https://github.com/Mbed-TLS/mbedtls/blob/development/library/psa_crypto_slot_management.c#L75-L77C4).

### Justification

Mbed TLS needs this because

**Comment by gilles-peskine-arm** [comment] 2023-07-18 17:45
Can you please clarify what the requirement is here? I have no idea what you mean by “there is only one slot for a volatile key”.

We already have an issue to track [protecting access to keys from concurrent threads](https://github.com/Mbed-TLS/mbedtls/issues/3263).

**Comment by gilles-peskine-arm** [comment] 2023-07-31 15:34
Ok, but I'm still not sure exactly what you want. Which scenario(s) do you want?

1. Thread A uses the PSA API and creates a key. Thread B uses the PSA API and creates a key.  
   The PSA API specification states that this should work, but it's a [known bug](https://github.com/Mbed-TLS/mbedtls/issues/3263) that it doesn't work in Mbed TLS . We intend to fix in Mbed TLS 3.6.  
   A partial workaround is to put your own mutex around key creation and destruction. This works for operations that do not use randomness.  For operations that do use randomness, this is a [known bug](https://github.com/Mbed-TLS/mbedtls/issues/3391) and there is no practical workaround.

2. Thread A uses the API API and creates a key. It passes the handle of that key to other threads which use the key.
   The PSA API specification states that this should work. In Mbed TLS, we don't yet guarantee anything, but in practice it does work for operations that don't use randomness. This will be fixed when (1) is fixed.

3. Thread A uses the PSA API and starts a multipart operation. Thread A passes the multipart operation object to thread B which continues the operation.
   The PSA API specification states that this should work, provided that the threads don't try to access the operation object concurrently. In Mbed TLS, we don't yet guarantee anything, but in practice it does work for operations that don't use randomness. This will be fixed when (1) is fixed.

4. Thread A uses the PSA API and starts a multipart operation. Thread A passes the multipart operation object to thread B. Threads A and B use the multipart operation object without doing any explicit synchronization.  
   I can't think of a scenario where this would be useful, since there's no control over the order in which the threads access the multipart operation.

5. Something else?

**Comment by lhuang04** [comment] 2023-07-31 16:23
> Which scenario(s) do you want?

We should be mostly in case 1. We don't have cases that a key will be passed from one thread to another. And we do randomness. So we may need the fix or [issue 3263](https://github.com/Mbed-TLS/mbedtls/issues/3263) and [issue 3391](https://github.com/Mbed-TLS/mbedtls/issues/3391).

**Comment by gilles-peskine-arm** [comment] 2023-07-31 18:05
> We should be mostly in case 1. We don't have cases that a key will be passed from one thread to another.

So this issue is a duplicate of https://github.com/Mbed-TLS/mbedtls/issues/3263 then?

> And we do need randomness

My bad, I was much more pessimistic about the current situation in my previous message. Use of randomness is ok if the random generator itself is protected, and this _is_ the case as long as you enable `MBEDTLS_THREADING_C`. We're only missing automatic protection around a custom RNG if there is one.

Also, I forgot to mention a scenario: multiple threads doing the initial call to `psa_crypto_init` at the same time. That one is not included in https://github.com/Mbed-TLS/mbedtls/issues/3263. It's difficult to resolve portably because there's no portable thread-safe way to initialize a mutex.

**Comment by paul-elliott-arm** [comment] 2024-03-18 12:38
Closing as I think this is resolved - please re-open or open a new ticket if necessary,

**Closed by paul-elliott-arm** 2024-03-18 12:38 UTC
Labels: needs-info
