### ISSUE TITLE
mbedtls_ssl_read: either documentation is partial (missing a call pre-condition), wrong or the implemented behavior is wrong

### ISSUE THREAD

**Issue by DBMTC** [Mbed-TLS/mbedtls#6899] opened 2023-01-10 15:12 UTC
### Summary
In ssl.h the function "mbedtls_ssl_read" has its return 0 case described as:
 
0 if the read end of the underlying transport was closed
without sending a CloseNotify beforehand, which might happen
because of various reasons (internal error of an underlying
stack, non-conformant peer not sending a CloseNotify and
such) - in this case you must stop using the context (see below).

but when used in non-blocking mode when the len parameter is zero, zero is returned from read and treated as EOF by the ctx->f_recv caller, thus returning 0 to the application that called mbedtls_ssl_read, that treats it as an error as per documentation: (quoting) "you must stop using the context".

No pre-condition is specified about len therefore zero is assumed an allowed value, but it's handled as an end-of-file by the current implementation.

### System information

Although still applying in most recent development commit at the time of writing (cd0a565) this was verified in the version included in esp-idf v4.4.

### Expected behavior

Either the return value does not indicate an error when zero bytes have been requested, the documentation reflects the fact that the len parameter cannot be zero or states that zero is returned even in case when the socket is still usable and no error has occurred. 

### Actual behavior

The return value of mbedtls_ssl_read when "len = 0" is zero, indicating an error

### Steps to reproduce

My use case is the following:

- set the socket to non-blocking
- do not set the f_recv_timeout callback
- do not set timer
- call mbedtls_ssl_read with len = 0 => this is because a ring buffer is used to temporary store application data, and it is passed to mbedtls_ssl_read as mbedtls_ssl_read(ctx, buffer + occupied, total - occupied), but occupied can be equal to total.

**Comment by paul-elliott-arm** [comment] 2023-01-12 14:28
Hi,

I am afraid this is indeed something of a bug. The problem with passing zero here is that it will return zero in both the success and EOF error case, and its impossible to differentiate between the two.

Unfortunately fixing this will be a rather major job, and given its in the public interface, this is unlikely to happen in the short term. There are definitely some plans to improve this area of the code, but I'm not sure at this time when they are planned for.

The best I can do for now is to make an edit to the documentation to point out the danger of passing in zero as a length here, if that is ok.

Is there any way you can detect the ring buffer being empty and prevent calling mbedtls_ssl_read() until it has some space in it again?

**Comment by paul-elliott-arm** [comment] 2023-01-12 14:50
Same issue: https://github.com/Mbed-TLS/mbedtls/issues/6625
Related: https://github.com/Mbed-TLS/mbedtls/pull/5527

**Comment by DBMTC** [comment] 2023-01-13 07:13
Hi,

Actually I have a way to check for zero-remaining space in the buffer and after this discovery I already implemented it so no problem on my side.

If it's a bug  or not really depends on the original API specification, but as long as it's described nobody will attempt to debug this again (hopefully) so editing the documentation seems the best option until that code area is improved.

Thanks

**Comment by paul-elliott-arm** [comment] 2023-01-13 18:39
Ok, closing as duplicate of #6625 - will look at fixing it there.

**Closed by paul-elliott-arm** 2023-01-13 18:39 UTC
Labels: bug, component-tls
