### ISSUE TITLE
Add accessor (getter/setter) function for mbedtls_ecp_keypair

### ISSUE THREAD

**Issue by priyamourya25** [Mbed-TLS/mbedtls#8367] opened 2023-10-16 14:16 UTC
### Suggested enhancement
Please add getter setter functions for members of struct mbedtls_ecp_keypair which are private now.

### Justification
These can be used to pass the group using mbedtls_ecp_group_load() API. Because members like "grp" are private, it can not be passed to load API without enabling private access.  

Mbed TLS needs this because we can then use the load API with the group in mbedtls_ecp_keypair.

**Comment by gilles-peskine-arm** [comment] 2023-10-16 14:39
We would prefer not to make the fields public, because that prevents us from improving support for platforms that have an ECC accelerator. We do recognize that the current API has gaps, however: we were planning improvements shortly after the 3.0 release, but they dropped off the radar.

We now hope to get https://github.com/Mbed-TLS/mbedtls/pull/7815 into the next release of Mbed TLS (3.6). Would that work for you? If not, could you please describe more precisely what you want to do with `mbedtls_ecp_keypair` object? Basically what you can do with `MBEDTLS_PRIVATE` but want to do without.

**Comment by minosgalanakis** [comment] 2023-11-13 15:49
Closing as a duplicate of #4838.  `ecp_export` [link ](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/ecp.h#L1343) can be used to extract the required fields.

Should that no be sufficient, please follow-up and comment on the actively workeed design issue #5017 dealing with the subject.

**Closed by minosgalanakis** 2023-11-13 15:49 UTC
Labels: enhancement, component-tls, size-s, needs-info, priority-high
