### ISSUE TITLE
Compilation failure due to invalid doc strings

### ISSUE THREAD

**Issue by boomer41** [Mbed-TLS/mbedtls#7146] opened 2023-02-21 17:46 UTC
### Summary

When compiling master and/or v3.3.0 with clang 15.0.7, the compiler complains that the documentation is invalid.
For the messages, please see "Actual behavior".

### System information

Mbed TLS version (number or commit id): v3.3.0
Operating system and version: ArchLinux
Configuration (if not default, please attach `mbedtls_config.h`): [mbedtls_config.h.zip](https://github.com/Mbed-TLS/mbedtls/files/10796166/mbedtls_config.h.zip)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): clang v15.0.7
Additional environment information: 

    clang version 15.0.7
    Target: x86_64-pc-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/12.2.1
    Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1
    Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1
    Candidate multilib: .;@m64
    Candidate multilib: 32;@m32
    Selected multilib: .;@m64`

### Expected behavior

Compilation works

### Actual behavior

Compiler complains that the documentation is invalid.
All include/psa/*.h-files are affected.

```
/usr/bin/clang  -I/home/user/project/lib/mbedtls/include -I/home/user/project/lib/mbedtls/library -I/home/user/project/lib -DMBEDTLS_CONFIG_FILE="<mbedtls_config.h>" -Wall -Wextra -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wvla -Wformat=2 -Wno-format-nonliteral -Werror -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O0 -g3 -fPIC -fvisibility=hidden -fcolor-diagnostics -std=c99 -MD -MT lib/mbedtls/library/CMakeFiles/smartcard_lib_mbedtls_mbedcrypto.dir/psa_crypto_driver_wrappers.c.o -MF lib/mbedtls/library/CMakeFiles/smartcard_lib_mbedtls_mbedcrypto.dir/psa_crypto_driver_wrappers.c.o.d -o lib/mbedtls/library/CMakeFiles/smartcard_lib_mbedtls_mbedcrypto.dir/psa_crypto_driver_wrappers.c.o -c /home/user/project/cmake-build-debug/lib/mbedtls/library/psa_crypto_driver_wrappers.c
In file included from /home/user/project/cmake-build-debug/lib/mbedtls/library/psa_crypto_driver_wrappers.c:25:
In file included from /home/user/project/lib/mbedtls/library/psa_crypto_aead.h:24:
/home/user/project/lib/mbedtls/include/psa/crypto.h:91:23: error: empty paragraph passed to '\retval' command [-Werror,-Wdocumentation]
 * \retval #PSA_SUCCESS
   ~~~~~~~~~~~~~~~~~~~^
/home/user/project/lib/mbedtls/include/psa/crypto.h:92:41: error: empty paragraph passed to '\retval' command [-Werror,-Wdocumentation]
 * \retval #PSA_ERROR_INSUFFICIENT_MEMORY
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

### Steps to reproduce

Compile v3.3.0 with clang 15

**Comment by tom-cosgrove-arm** [comment] 2023-02-21 19:12
Closing as this is a duplicate of #6960, for which we have two alternative PRs in review: #6966 and #7098

**Closed by tom-cosgrove-arm** 2023-02-21 19:12 UTC
