### ISSUE TITLE
mbedtls_ssl_read() documentation is ambiguous

### ISSUE THREAD

**Issue by KloolK** [Mbed-TLS/mbedtls#6625] opened 2022-11-18 14:25 UTC
It is unclear whether it is legitimate to call mbedtls_ssl_read() with len = 0.
The documentation does not prohibit len = 0:
https://github.com/Mbed-TLS/mbedtls/blob/869298bffeea13b205343361b7a7daf2b210e33d/include/mbedtls/ssl.h#L4584-L4588

However, the expected return value of 0 is already used to indicate an error. There is no way to distinguish between a "successful" read of 0 bytes and an error condition:
https://github.com/Mbed-TLS/mbedtls/blob/869298bffeea13b205343361b7a7daf2b210e33d/include/mbedtls/ssl.h#L4590-L4596

For a use-case where len = 0 might provide some practical use, please see my related question on the mbedtls mailing list: https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/message/N6ZOBZHIJIORS62RAWDY4X2BEKOOMLR5/

**Comment by minosgalanakis** [comment] 2022-11-22 17:12
Thanks you for your report. This issue relates to #3076 and is addressed by #5527 .

Reading zero should be a no-op but the implementation of memcpy does not strictly enforce it. I will be ammending the documentation and bringing the PR changes forward, in order to more clearly state what the intent is.

**Comment by gilles-peskine-arm** [comment] 2023-01-12 17:33
@minosgalanakis The problem isn't just the implementation bug, or the documentation. It seems that there is an ambiguity in the interface itself. If you call `mbedtls_ssl_read` with `len=0` and it returns 0, how do you know whether this indicates that all is well, or this indicates that the peer has closed the connection?

I don't see an easy fix since this either changes the expectations of existing code that assumes that return=0 is always an error, or changes the expectations of existing code that assumes that return=len is always a success.

`mbedtls_ssl_read(0)` does not seem very useful at first glance, but it could be a way to check whether the peer has closed the connection, without consuming any data. Except that the return value is 0 in both cases.

The use case in https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/message/N6ZOBZHIJIORS62RAWDY4X2BEKOOMLR5/ involves reading private fields, so it is not officially supported. (I can see how it would be useful, but that would be a new feature, not a bug fix.)

A possible way to handle this without changing the API of `mbedtls_ssl_read` would be to add a function to check whether a context is valid, which is something we've wanted to do for a while. (Because the conditions that invalidate a context are subtle, even in cases that are not outright ambiguous.) That itself is not a trivial project.

**Comment by mpg** [comment] 2023-01-23 08:21
Note: I'm not a big fan of the fact that we have one where returning 0 means something is wrong - all other functions return a negative value on errors. I get that this is to mimic POSIX `read()`, but I'm not sure this is a good enough reason.

While I agree with Gilles's proposal for the short term, in the long run I'm wondering if it might be better to change that API at the next opportunity (that is, Mbed TLS 4.0) so that it returns negative on errors like all other Mbed TLS functions. That would also avoid this ambiguity.

**Closed** 2023-03-13 10:46 UTC
Labels: bug, component-tls
