### ISSUE TITLE
SSLlabs.com test fails

### ISSUE THREAD

**Issue by Aethedor** [Mbed-TLS/mbedtls#8995] opened 2024-03-29 20:04 UTC
### Summary
I use mbed TLS in my Hiawatha webserver. I updated to version 3.6.0 and enabled TLS v1.3 support. (btw, congrats with this new milestone!) It seems to work fine, but SSLlabs.com shows a failure while testing my server. When I only support TLS v1.3 (disabling TLS v1.2) the test runs fine. Same with only supporting TLS v1.2 (not enabling TLS v1.3).

### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: Ubuntu Linux (Jammy)
Configuration (if not default, please attach `mbedtls_config.h`):
I enabled the following settings:
MBEDTLS_THREADING_PTHREAD
MBEDTLS_THREADING_C
MBEDTLS_SSL_PROTO_TLS1_3
MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE

I disabled the following settings:
MBEDTLS_ECP_DP_SECP192R1_ENABLED
MBEDTLS_ECP_DP_SECP192K1_ENABLED

Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
I hoped SSLlabs.com would show the result of a server test.

### Actual behavior
SSLlabs.com shows a failure while testing renegotation.

### Steps to reproduce
Visit ssllabs.com, select Test your server and test www.hiawatha-webserver.org

### Additional information
You can test Hiawatha v11.6 (not yet released) which has mbed TLS v3.6.0 by downloading it via https://www.leisink.net/hiawatha-11.6.tar.gz

**Comment by bensze01** [comment] 2024-04-10 08:56
Hi! Thanks for reporting this issue.

Could you help us debug this by providing some more information about exactly which SSLLabs tests are failing?

As far as I can tell, SSLLabs is just reporting an "Unexpected Failure", which they claim is usually caused by having multiple "Multiple TLS servers behind the same IP address".

Also, it looks like the download link for the unreleased Hiawatha 11.6 is broken.

**Comment by Aethedor** [comment] 2024-04-10 09:17
The test fails after saying 'Testing renegotiation'. Does that help? I can share a tcpdump of the scan. I'm willing to help, let me know what you need.

The download link was a http:// link by mistake. Changed it to https://. Should work.

**Comment by Aethedor** [comment] 2024-04-10 12:58
I use mbedtls_ssl_conf_renegotiation(&client_config, MBEDTLS_SSL_RENEGOTIATION_DISABLED) to disable it. Would that be the same?

**Comment by bensze01** [comment] 2024-04-10 14:36
In principle it should be equivalent. Please send the tcpdump to bence.szepkuti@arm.com

**Comment by bensze01** [comment] 2024-04-10 14:51
Could you also enable [TLS debugging in MbedTLS](https://mbed-tls.readthedocs.io/en/latest/kb/development/debugging-tls/) and send me the logs?

**Comment by Aethedor** [comment] 2024-04-10 15:55
TCPdumps for TLS1.2 only, TLS1.3 only and both TLS1.2 and TLS1.3 has been sent. I've added the corresponding ssllabs.com output. I've also send a Mbed TLS debug logfile of the failing both-TLS1.2-and-TLS1.3 test.

**Comment by Aethedor** [comment] 2024-04-16 20:36
Mail received? What's next?

**Comment by Aethedor** [comment] 2024-04-22 14:47
Anything yet?

**Comment by Aethedor** [comment] 2024-05-16 11:54
Any status update?

**Comment by Aethedor** [comment] 2024-06-10 12:05
Can I assume this bug has no priority? Then I'll ignore it from now on.

**Comment by waleed-elmelegy-arm** [comment] 2024-06-12 12:03
Hi @Aethedor ,
I think I found the reason to your problem, it is described in #9243 but I can't test with SSLlabs.com to double check, can you try the patch at #9244 and see if it works? Thanks.

**Comment by waleed-elmelegy-arm** [comment] 2024-08-27 10:23
Fixed in #9244

**Closed by waleed-elmelegy-arm** 2024-08-27 10:23 UTC
Labels: bug, component-tls13
